### ISSUE TITLE
Add greetings and goodbye tags, their patterns and responses to intents.json

### ISSUE THREAD

**Issue by UjjwalAnand364** [UjjwalAnand364/Self-Intelligent-Chatbot#2]
Sample has been shown in the intents.json file. Add more such commonly used phrases in speech, to patterns and responses. Edit in the Working branch.

**Comment by aayushsinha0706** [comment]
hello would like to work on this issue

**Comment by UjjwalAnand364** [comment]
Yes you are welcome! I would be creating more issues in the coming days to which you can contribute.

**Comment by guptamanas7** [comment]
Hello, I would like to work on this.
please assign this to me

**Comment by UjjwalAnand364** [comment]
Hi, welcome.
This issue is completed, you can work on another version of this issue, where you need to add the mentioned phrases. I have given the link below or you can go to issues and complete it.
https://github.com/UjjwalAnand364/Self-Intelligent-Chatbot/issues/3
